apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-service-config
  namespace: uim-vault
data:
  PORT: "8080"
  BIND_ADDRESS: "0.0.0.0"
  VAULT_SERVER_NAME: "uim-vault-service"
  VAULT_SERVER_VERSION: "0.1.0"
  VAULT_DEFAULT_TTL_SECONDS: "3600"
