apiVersion: v1
kind: Service
metadata:
  name: uim-kafka-service
  namespace: uim-kafka
  labels:
    app: uim-kafka-service
spec:
  type: ClusterIP
  selector:
    app: uim-kafka-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
