apiVersion: v1
kind: Service
metadata:
  name: uim-odata-service
  namespace: uim-odata
  labels:
    app: uim-odata-service
spec:
  type: ClusterIP
  selector:
    app: uim-odata-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
