apiVersion: v1
kind: Service
metadata:
  name: uim-terraform-service
  namespace: uim-terraform
spec:
  selector:
    app: uim-terraform-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
