apiVersion: v1
kind: ConfigMap
metadata:
  name: block-storage-service-config
  namespace: uim-block-storage
data:
  PORT: "8080"
  BIND_ADDRESS: "0.0.0.0"
  PID_FILE: "/var/run/uim-block-storage-service.pid"
