apiVersion: v1
kind: Service
metadata:
  name: uim-ui5-server-service
  namespace: uim-ui5-server
  labels:
    app: uim-ui5-server-service
spec:
  type: ClusterIP
  selector:
    app: uim-ui5-server-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
