apiVersion: v1
kind: Service
metadata:
  name: uim-cds-service
  namespace: uim-cds
spec:
  selector:
    app: uim-cds-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
