apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-relay-config
  namespace: uim-smtp-relay
data:
  PORT: "8080"
  BIND_ADDRESS: "0.0.0.0"
  PID_FILE: "/tmp/uim-smtp-relay-service.pid"
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
  SMTP_FROM: "noreply@uim.local"
  SMTP_SECURITY: "plain"
  SMTP_AUTH: "none"
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  STORE_BACKEND: "file"
  MESSAGE_STORE_PATH: "/data/messages.json"
